// src/components/CategoryRow.tsx
import React from "react";
import store from "../store";
import { Category } from "../store/CategoryStore";
import "./CategoryRow.scss";
import SimpleRow from "./SimpleRow";

const CategoryRow: React.FC<{
    category: Category;
    className: string;
}> = ({ category, className }) => {
    return (
        <SimpleRow
            className={className}
            slug={category.slug}
            onClick={handleClick}
            line1={`${category.name} (${category.exhibitors.length})`}
            line2="Category"
        />
    );
    function handleClick() {
        store.clickCategory(category);
    }
};

export default CategoryRow;

// src/components/CategoryRow.vue
<template>
    <SimpleRow :slug="category.slug" @click="click" :line1="`${category.name} (${numOfExhibitors})`" line2='Category' />
</template>

<script lang="ts">

import SimpleRow from "./SimpleRow.vue";

export default {
    name: "CategoryRow",
    components: { SimpleRow },
    props: ["category"],
    methods: {
        click() {
            this.$store.dispatch("clickCategory", this.category.id);
        },
    },
    computed: {
        numOfExhibitors: function () {
            return this.$store.getters.exhibitorsArray.filter(e =>
                e.categories.indexOf(this.category.id) !== -1).length;
        }
    }
};
</script>

<style lang="scss">
</style>
