// src/components/Exhibitor.vue
<template>
    <OverlayContent class='exhibitor' v-if="show" :class={bookmarked} back-mode=none @close='$store.dispatch("selectNone")'>
        <template slot="bar">
            <div class="exhibitor__bar">
                <span @click='$store.dispatch("toggleMapOverlay")'>
                    <span>{{exhibitor.name}} </span>
                    <i class="fas fa-gem" v-if='featured'></i>
                </span>
                <a href='' @click.prevent="bookmark" class="exhibitor__bar-bk">
                    <BookmarkSvg />
                </a>
            </div>
            <div class="exhibitor__bar-booth" @click='$store.dispatch("toggleMapOverlay")'>{{__data.boothTerm}}
                <span v-for="booth in booths" :key="booth.id">
                    {{booth.name}}
                </span></div>
        </template>
        <div class="exhibitor__details">
            <div class="exhibitor__categories">
                <a href='' v-for="booth in booths" :key="booth.id" @click.prevent='$store.dispatch("toggleMapOverlay")'
                    class="exhibitor__categories-booth">{{__data.boothTerm}} {{booth.name}}</a>
                <a :href='"?" + encodeURIComponent(c.slug)' v-for="c in categories" :key="c.id" @click.prevent="handleCategoryClick(c)"
                    class="exhibitor__categories-cat">{{c.name}}</a>
            </div>
            <div class="exhibitor__description" :class='{collapsed : collapsed && !disableCollapse}' v-if="exhibitor.description || exhibitor.logo">
                <div class='exhibitor__logo-container' v-if="exhibitor.logo">
                    <img :src="exhibitor.logo" class="exhibitor__logo" :key='exhibitor.id'>
                </div>
                <span class="exhibitor__description-html" v-html="exhibitor.description" @click='collapsed=false'></span>
            </div>
            <div class="exhibitor__sep" v-if=anyAddress></div>
            <div class="exhibitor__edit" v-if=showEdit><button class="far fa-pencil" title="Edit" @click="sendLoginLink"></button></div>
            <div class="exhibitor__meta" v-if=anyAddress>
                <div v-if="exhibitor.address || exhibitor.address2">
                    <i class="fas fa-map-marker"></i>
                    <div>
                        {{exhibitor.address}}
                        <div v-if="exhibitor.address2">{{exhibitor.address2}}</div>
                        <div v-if="exhibitor.city || exhibitor.state || exhibitor.zip">
                            {{exhibitor.city}}<span v-if="exhibitor.city && exhibitor.state">,</span>
                            {{exhibitor.state}}
                            {{exhibitor.zip}}
                        </div>
                        <div v-if="exhibitor.country">{{exhibitor.country}}</div>
                    </div>
                </div>
                <div v-if="exhibitor.phone1">
                    <i class="fas fa-phone"></i>
                    <div>
                        <a :href="'tel:'+exhibitor.phone1">{{exhibitor.phone1}}</a>
                    </div>
                </div>
                <div v-if="exhibitor.website">
                    <i class="fas fa-globe"></i>
                    <div>
                        <a :href="exhibitor.website" target="_blank">{{websiteTrimmed}}</a>
                    </div>
                </div>
                <div v-if="exhibitor.email">
                    <i class="fas fa-at"></i>
                    <div>
                        <a :href="'mailto:' + exhibitor.email" target="_blank">{{exhibitor.email}}</a>
                    </div>
                </div>
            </div>
            <div class="exhibitor__sep" v-if=anySocial></div>
            <div class="exhibitor__social" v-if='anySocial'>
                <a :href="exhibitor.facebook" target="_blank">
                    <i class='fab fa-facebook'></i>
                </a>
                <a :href="exhibitor.instagram" target="_blank">
                    <i class='fab fa-instagram'></i>
                </a>
                <a :href="exhibitor.linkedin" target="_blank">
                    <i class='fab fa-linkedin'></i>
                </a>
                <a :href="exhibitor.twitter" target="_blank">
                    <i class='fab fa-twitter'></i>
                </a>
                <a :href="exhibitor.googlePlus" target="_blank">
                    <i class='fab fa-google-plus'></i>
                </a>
                <a :href="exhibitor.xing" target="_blank">
                    <i class='fab fa-xing'></i>
                </a>
                <a :href="exhibitor.youtube" target="_blank">
                    <i class='fab fa-youtube'></i>
                </a>
            </div>
        </div>
    </OverlayContent>

</template>

<script lang="ts">
import { mapGetters, mapState } from "vuex";
import OverlayContent from "./OverlayContent.vue";
import BookmarkSvg from "./BookmarkSvg.vue";

export default {
    components: { OverlayContent, BookmarkSvg },
    data: () => ({ collapsed: true }),
    computed: {
        ...mapState(["menu", "details"]),
        ...mapGetters(["overlayPosition"]),
        show() {
            return !this.menu && this.details && this.details.type === "exhibitor";
        },
        exhibitor() {
            return this.$store.getters.selectedExhibitor;
        },
        booths() {
            return this.exhibitor.booths.map(b => this.$store.state.booths[b]);
        },
        categories() {
            return this.exhibitor.categories.map(b => this.$store.state.categories[b]);
        },
        websiteTrimmed() {
            return this.exhibitor.website ? this.exhibitor.website.replace(/^(http(s?):\/\/)([^/]+)(\/)?$/i, "$3") : "";
        },
        bookmarked() {
            return this.$store.state.bookmarked[this.exhibitor.id];
        },
        featured() {
            return this.exhibitor.featured;
        },
        anySocial() {
            return !!["facebook", "instagram", "linkedin", "twitter", "googlePlus", "xing", "youtube"].find(
                s => this.exhibitor[s]
            );
        },
        anyAddress() {
            return !!["address", "address2", "phone1", "website", "email"].find(
                s => this.exhibitor[s]
            );
        },
        disableCollapse() {
            return !this.anySocial && !this.anyAddress || this.overlayPosition === "left" && (this.exhibitor.description || '').length < 800;
        },
        showEdit() {
            return __data.sendLoginLinkUrl && this.sendLinkEmail;
        },
        sendLinkEmail() {
            return this.exhibitor.privateEmail || this.exhibitor.email;
        }
    },
    watch: {
        exhibitor() {
            this.$el.parentElement.scrollTop = 0;
            this.collapsed = true;
        }
    },
    methods: {
        handleCategoryClick(c) {
            this.$store.dispatch("selectCategory", c.id);
        },
        sendLoginLink(e) {
            e.target.blur();
            const email = this.sendLinkEmail;
            if (!confirm(`Send login instructions to ${email} to edit profile?`)) return;
            if (EFP_EXPO !== "expo") return;
            const xhr = new XMLHttpRequest();
            xhr.open("POST", __data.sendLoginLinkUrl);
            xhr.setRequestHeader("Content-Type", "application/json");
            function er() {
                alert("Error sending login instructions.");
            }
            xhr.onload = function (e) {
                if (this.status !== 200) {
                    er();
                    return;
                }
                alert(`A link to edit profile was sent to ${email}.`)
            };
            xhr.onerror = function (e) {
                __logger.error("Error", e);
                er();
            };
            xhr.send(JSON.stringify({ "id": this.exhibitor.id }));
        },
        bookmark() {
            this.$store.commit("setBookmarked", { id: this.exhibitor.id, yes: !this.bookmarked });
        }
    }
};
</script>

<style lang="scss">
.expo-jtrade19 .exhibitor__categories-booth {
    background: #e9522a; //#fb3e59;
    &:hover {
        background: #e9522a; //#ea2b46;
    }
}
.exhibitor {
    // &__booth {
    //     margin: 0 1rem 0.2rem;
    //     color: #777;
    // }
    &__categories {
        margin: 0rem 1rem 1rem 0.7rem;
        font-size: 0.9rem;
        // display: flex;
        // flex-direction: column;
        // align-items: flex-start;
        > a {
            display: inline-block;

            color: #fff !important;
            font-size: 0.8rem;
            padding: 0.3rem 0.6rem;
            border-radius: 1em;
            margin: 0.3rem 0 0 0.3rem;
            text-decoration: none !important;
        }

        &-cat {
            background: #41b6e7;
            &:hover {
                background: #1598d0;
            }
        }

        &-booth {
            background: #fb3e59;
            &:hover {
                background: #ea2b46;
            }
        }
    }
    &__logo-container {
        width: 75px;
        height: 75px;
        float: left;
        margin: 0.3rem 0.8rem 0.4rem 0;
        border: solid 1px #ddd;
        border-radius: 5px;
        overflow: hidden;
        display: flex;
        align-items: center;
        position: relative; 
        z-index: 2;
    }
    &__logo {
        max-width: 100%;
        max-height: 100%;

        // height: 75px;
    }
    &__description {
        margin: 1rem;
        font-size: 0.9rem;
        color: #444;
        position: relative;
        

        /* &-show {
            display: none;
            position: absolute;
            z-index: 2;
            bottom: -0.7em;
            width: 100%;
            padding-left: 87px;
            // text-align: center;
            // display: block;
            // font-size: 2rem;
            text-decoration: none !important;
        } */

        &-html{
            > *:first-child {
                margin-top: 0;
                padding-top: 0;
            }
        }

        &.collapsed > .exhibitor__description-html {
            cursor: pointer;
            &:hover {
                color: #000;
            }
            height: 6.5em;
            display: block;
            overflow: hidden;
            text-overflow: ellipsis;
            &:after {
                content: "";
                position: absolute;
                z-index: 1;
                bottom: 0;
                left: 0;
                pointer-events: none;
                background-image: linear-gradient(to bottom, rgba(255, 255, 255, 0), rgba(255, 255, 255, 1) 90%);
                width: 100%;
                height: 4em;
            }
        }

        @include clearfix;
    }

    &__sep {
        margin: 1rem;
        border-top: dotted 1px #ddd;
    }

    &__meta {
        > div {
            display: flex;
            margin: 0.8rem 1rem;
            overflow: hidden;

            > .fas,
            > .far {
                text-align: center;
                min-width: 0.8rem;
                margin-top: 0.2rem;
                color: #ccc;
                font-size: 0.8rem;
            }
            > div {
                font-size: 0.85rem;
                line-height: 1.1rem;
                color: #333;
                margin-left: 0.4rem;
                text-overflow: ellipsis;
                overflow: hidden;
                // font-weight: 200;
            }
        }
    }
    &__social {
        margin: 0 1rem 2rem;

        display: flex;
        // justify-content: space-between;
        // padding-top: 1rem;
        > a {
            font-size: 2rem;
            text-decoration: none;

            margin: 0 1rem 0.5rem 0;
            color: #eee;
            display: none;
            &:hover {
                color: #eee;
            }
            &[href] {
                display: block;
                color: var(--link-color);

                &:hover {
                    color: var(--link-color-hover);
                }
            }
        }
    }

    &__bar {
        min-height: 2.5rem;
        position: relative;
        line-height: 1.5rem;
        color: #333;
        font-weight: 500;
        padding-top: 1rem;
        margin-left: 1rem;
        font-size: 1.1em;
        flex-grow: 1;
        // display: flex;
        // align-items: center;
        .fa-gem {
            color: #02a8ff;
            margin-left: 0.2rem;
            font-size: 0.85rem;
            line-height: 1.5rem;
        }
        > span {
            display: flex;
            > span {
                white-space: nowrap;
                max-width: 18rem;
                overflow: hidden;
                text-overflow: ellipsis;
            }
        }
    }
    &__bar-booth {
        margin-left: 1rem;
        font-size: 0.7rem;
        color: #777;
        display: block;
        font-weight: normal;
        height: 1rem;
        line-height: 1em;
        opacity: 0;
        transition: opacity 200ms;
        .overlay-bar.scrolled & {
            opacity: 1;
        }
    }

    &__bar-bk {
        position: absolute;
        right: 0;
        top: 0;
        padding: 0 1rem 1rem 1rem;
        /* align-self: stretch; */
    }

    &__edit {
        position: relative;
        display: none;
        > button {
            position: absolute;
            right: 1rem;
            padding: 0 0 1rem 1rem;
            border: 0;
            cursor: pointer;
            color: #aaa;
            &:hover {
                color: #555;
            }
        }

        .exhibitor__details:hover > & {
            display: block;
        }
    }
}
</style>

// src/components/Exhibitor.tsx
import classNames from "classnames";
import { useLocalStore, useObserver } from "mobx-react-lite";
import React, { MouseEvent, useRef } from "react";
import data from "../data";
import store, { uiState } from "../store";
import { Category } from "../store/CategoryStore";
import logger from "../tools/logger";
import settings from "../tools/settings";
import { useReaction } from "../utils/mobx";
import BookmarkSvg from "./BookmarkSvg";
import "./Exhibitor.scss";
import OverlayContent from "./OverlayContent";

function ExhibitorComponent() {
    const el = useRef<HTMLDivElement>();
    const s = useLocalStore(() => ({
        collapsed: true,

        get exhibitor() {
            return uiState.selectedExhibitor;
        },
        get websiteTrimmed() {
            return this.exhibitor.website ? this.exhibitor.website.replace(/^(http(s?):\/\/)([^/]+)(\/)?$/i, "$3") : "";
        },
        get anySocial() {
            if (uiState.kiosk) return false;
            return !!["facebook", "instagram", "linkedin", "twitter", "googlePlus", "xing", "youtube"].find(
                s => this.exhibitor[s]
            );
        },
        get anyAddress() {
            return !!["address", "address2", "phone1", "website", "email"].find(s => this.exhibitor[s]);
        },
        get disableCollapse() {
            return (
                (!this.anySocial && !this.anyAddress) ||
                (uiState.overlayPosition === "left" && (this.exhibitor.description || "").length < 800)
            );
        },
        get showEdit() {
            return !!(data.sendLoginLinkUrl && this.sendLinkEmail);
        },
        get sendLinkEmail() {
            return this.exhibitor.privateEmail || this.exhibitor.email;
        }
    }));

    useReaction(
        () => s.exhibitor,
        () => {
            if (el.current) el.current.parentElement.scrollTop = 0;
            s.collapsed = true;
        }
    );

    function handleClick(e) {
        if (uiState.kiosk) return e.preventDefault();
    }

    return useObserver(() => {
        const exhibitor = s.exhibitor;
        // if (!exhibitor) return null;
        const bar = (
            <>
                <div className="exhibitor__bar">
                    <span onClick={() => store.toggleMapOverlay()}>
                        <span>{exhibitor.name}</span>
                        {exhibitor.featured ? <i className="fas fa-gem" /> : null}
                    </span>
                    {uiState.kiosk ? null : (
                        <a href="/" onClick={bookmark} className="exhibitor__bar-bk">
                            <BookmarkSvg />
                        </a>
                    )}
                </div>
                <div className="exhibitor__bar-booth" onClick={() => store.toggleMapOverlay()}>
                    {data.boothTerm} {exhibitor.booths.map(b => b.name).join(", ")}
                </div>
            </>
        );

        const cls = classNames({
            exhibitor: true,
            "-exhibitor-featured": exhibitor.featured,
            bookmarked: exhibitor.bookmarked
        });

        return (
            <OverlayContent
                className={cls}
                backMode="none"
                onClose={() => store.selectNone()}
                particles={exhibitor.featured}
                bar={bar}
            >
                <div className="exhibitor__details">
                    <div className="exhibitor__categories">
                        {exhibitor.booths.map(booth => (
                            <a
                                href={`?${exhibitor.slug}`}
                                key={booth.id}
                                onClick={e => {
                                    e.preventDefault();
                                    store.toggleMapOverlay();
                                }}
                                className="exhibitor__categories-booth"
                            >
                                {data.boothTerm} {booth.name}
                            </a>
                        ))}
                        {exhibitor.categories.map(c => (
                            <a
                                href={"?" + encodeURIComponent(c.slug)}
                                key={c.id}
                                onClick={e => {
                                    e.preventDefault();
                                    handleCategoryClick(c);
                                }}
                                className="exhibitor__categories-cat"
                            >
                                {c.name}
                            </a>
                        ))}
                    </div>
                    {exhibitor.description || exhibitor.logo ? (
                        <div
                            className={classNames({ exhibitor__description: true, collapsed: s.collapsed && !s.disableCollapse })}
                        >
                            {exhibitor.logo ? (
                                <div className="exhibitor__logo-container" v-if="exhibitor.logo">
                                    <img src={exhibitor.logo} className="exhibitor__logo" alt={exhibitor.name} />
                                </div>
                            ) : null}
                            {exhibitor.description ? (
                                <span
                                    className="exhibitor__description-html"
                                    dangerouslySetInnerHTML={{ __html: exhibitor.description }}
                                    onClick={() => (s.collapsed = false)}
                                />
                            ) : null}
                        </div>
                    ) : null}
                    {s.anyAddress ? <div className="exhibitor__sep" /> : null}
                    {s.showEdit ? (
                        <div className="exhibitor__edit">
                            <button className="far fa-pencil" title="Edit" onClick={sendLoginLink} />
                        </div>
                    ) : null}
                    {s.anyAddress && (
                        <div className="exhibitor__meta">
                            {!!(exhibitor.address || exhibitor.address2) && (
                                <div>
                                    <i className="fas fa-map-marker" />
                                    <div>
                                        {exhibitor.address}
                                        {!!exhibitor.address2 && <div>{exhibitor.address2}</div>}
                                        {!!(exhibitor.city || exhibitor.state || exhibitor.zip) && (
                                            <div>
                                                {exhibitor.city}
                                                {!!(exhibitor.city && exhibitor.state) && <span>,</span>}
                                                {exhibitor.state} {exhibitor.zip}
                                            </div>
                                        )}
                                        {!!exhibitor.country && <div>{exhibitor.country}</div>}
                                    </div>
                                </div>
                            )}
                            {!!exhibitor.phone1 && (
                                <div>
                                    <i className="fas fa-phone" />
                                    <div>
                                        <a href={"tel:" + exhibitor.phone1} onClick={handleClick}>
                                            {exhibitor.phone1}
                                        </a>
                                    </div>
                                </div>
                            )}
                            {!!exhibitor.website && (
                                <div>
                                    <i className="fas fa-globe" />
                                    <div>
                                        <a
                                            href={exhibitor.website}
                                            target="_blank"
                                            rel="noopener noreferrer"
                                            onClick={handleClick}
                                        >
                                            {s.websiteTrimmed}
                                        </a>
                                    </div>
                                </div>
                            )}
                            {!!exhibitor.email && (
                                <div v-if="exhibitor.email">
                                    <i className="fas fa-at" />
                                    <div>
                                        <a
                                            href={"mailto:" + exhibitor.email}
                                            target="_blank"
                                            rel="noopener noreferrer"
                                            onClick={handleClick}
                                        >
                                            {exhibitor.email}
                                        </a>
                                    </div>
                                </div>
                            )}
                        </div>
                    )}
                    {s.anySocial && <div className="exhibitor__sep" />}
                    {s.anySocial && (
                        <div className="exhibitor__social">
                            <a href={exhibitor.facebook} target="_blank" rel="noopener noreferrer">
                                <i className="fab fa-facebook" />
                            </a>
                            <a href={exhibitor.instagram} target="_blank" rel="noopener noreferrer">
                                <i className="fab fa-instagram" />
                            </a>
                            <a href={exhibitor.linkedin} target="_blank" rel="noopener noreferrer">
                                <i className="fab fa-linkedin" />
                            </a>
                            <a href={exhibitor.twitter} target="_blank" rel="noopener noreferrer">
                                <i className="fab fa-twitter" />
                            </a>
                            <a href={exhibitor.googlePlus} target="_blank" rel="noopener noreferrer">
                                <i className="fab fa-google-plus" />
                            </a>
                            <a href={exhibitor.xing} target="_blank" rel="noopener noreferrer">
                                <i className="fab fa-xing" />
                            </a>
                            <a href={exhibitor.youtube} target="_blank" rel="noopener noreferrer">
                                <i className="fab fa-youtube" />
                            </a>
                        </div>
                    )}
                </div>
            </OverlayContent>
        );
    });

    function handleCategoryClick(c: Category) {
        store.selectCategory(c);
    }

    function sendLoginLink(e: MouseEvent<HTMLButtonElement>) {
        if (uiState.kiosk) return e.preventDefault();

        (e.target as HTMLDivElement).blur();
        const email = s.sendLinkEmail;
        if (!window.confirm(`Send login instructions to ${email} to edit profile?`)) return;
        if (settings.EXPO === "expo") return;
        const xhr = new XMLHttpRequest();
        xhr.open("POST", data.sendLoginLinkUrl);
        xhr.setRequestHeader("Content-Type", "application/json");
        function er() {
            alert("Error sending login instructions.");
        }
        xhr.onload = function(e) {
            if (this.status !== 200) {
                er();
                return;
            }
            alert(`A link to edit profile was sent to ${email}.`);
        };
        xhr.onerror = function(e) {
            logger.error("Error", e);
            er();
        };
        xhr.send(JSON.stringify({ id: s.exhibitor.id }));
    }

    function bookmark(e: MouseEvent) {
        e.preventDefault();
        s.exhibitor.bookmarked = !s.exhibitor.bookmarked;
    }
}

export default () => useObserver(() => <>{!uiState.menu && uiState.selectedExhibitor ? <ExhibitorComponent /> : null}</>);
