// _oldsrc/components/ExhibitorRow.vue
<template>
    <a class="exhibitor-row" :class="{bookmarked, featured}" @mouseover="mouseover" @mouseout="mouseout" :href="`?${exhibitor.slug}`"
        @click.prevent="select">
        <div class="exhibitor-row__lines">
            {{exhibitor.name}} <i class="fas fa-gem" v-if='featured'></i>
        </div>
        <div ref="bookmark" class="exhibitor-row__bookmark" tabindex="0" @click.prevent.stop="bookmark" title="Toggle bookmark">
            <BookmarkSvg />
        </div>
        <div class="exhibitor-row__booth">
            <div v-for="booth in booths" :key="booth.id">
                {{booth.name}}
            </div>
        </div>
    </a>
</template>

<script lang="ts">
import BookmarkSvg from "./BookmarkSvg.vue";

export default {
    name: "ExhibitorRow",
    props: ["exhibitor"],
    components: { BookmarkSvg },
    methods: {
        select() {
            this.$store.dispatch("clickExhibitor", this.exhibitor.id);
        },
        bookmark() {
            this.$refs.bookmark.blur();
            this.$store.commit("setBookmarked", { id: this.exhibitor.id, yes: !this.bookmarked });
        },
        mouseover() {
            if (this.$store.state.hoveredExhibitor !== this.exhibitor.id) {
                this.$store.commit("setHoveredExhibitor", this.exhibitor.id);
            }
        },
        mouseout() {
            this.$store.commit("setHoveredExhibitor", null);
        }
    },
    computed: {
        booths() {
            return this.exhibitor.booths.map(e => this.$store.state.booths[e]);
        },
        bookmarked() {
            return this.$store.state.bookmarked[this.exhibitor.id];
        },
        featured() {
            return this.exhibitor.featured;
        }
    }
};
</script>

<style lang="scss">
.exhibitor-row {
    display: flex;
    align-items: center;
    text-decoration: none !important;
    color: #333 !important;

    &.featured {
        .exhibitor-row__lines {
            font-weight: 700;
        }
    }

    &__lines {
        padding: 0 0.1rem 0 1rem;
        flex-grow: 1;

        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
        > .fa-gem {
            color: #02a8ff;
            font-size: 0.9rem;
        }
    }
    &__booth {
        padding: 0 1rem 0 0;
        min-width: 3.5rem;
        text-align: right;
        font-weight: 700;
        font-size: 0.9rem;
        color: #555;
    }

    &__bookmark {
        align-self: stretch;
        padding: 0 0.5rem 0 1rem;
        outline: none;
    }
}
</style>

// src/components/ExhibitorRow.tsx
import classNames from "classnames";
import { useObserver } from "mobx-react-lite";
import React, { MouseEvent, useEffect, useRef } from "react";
import { RegularBooth } from "../core/Booth";
// import store, { uiState } from "../store";
import { Exhibitor } from "../store/ExhibitorStore";
import { useStore, useUiState } from "../tools/use";
import BookmarkSvg from "./BookmarkSvg";
import "./ExhibitorRow.scss";

const ExhibitorRow: React.FC<{ exhibitor: Exhibitor; className: string }> = ({ exhibitor, className }) => {
    const store = useStore();
    const uiState = useUiState();
    // const exhibitorStore = useExhibitorStore();

    function handleClick(e: MouseEvent) {
        e.preventDefault();
        store.clickExhibitor(exhibitor);
    }

    function handleBookmark(e: MouseEvent) {
        e.preventDefault();
        e.stopPropagation();
        if (document.activeElement) (document.activeElement as HTMLDivElement).blur();
        store.toggleExhibitorBookmark(exhibitor);
        // if (exhibitor.bookmarked) {
        //     exhibitorStore.bookmarked.delete(exhibitor.id);
        // } else {
        //     exhibitorStore.bookmarked.add(exhibitor.id);
        // }

        //exhibitor.bookmarked = !exhibitor.bookmarked;
    }

    const div = useRef();

    useEffect(() => {
        (div.current as HTMLAnchorElement).tabIndex = 0;
    }, [div]);

    return useObserver(() => (
        <a
            className={`exhibitor-row ${className} ${classNames({
                bookmarked: exhibitor.bookmarked,
                featured: exhibitor.featured
            })}`}
            onMouseOver={() => (uiState.hoveredExhibitor = exhibitor)}
            onMouseOut={() => (uiState.hoveredExhibitor = null)}
            href={`?${exhibitor.slug}`}
            onClick={handleClick}
        >
            <div className="exhibitor-row__lines">
                {exhibitor.name} {exhibitor.featured ? <i className="fas fa-gem" /> : null}
            </div>
            <div className="exhibitor-row__bookmark" onClick={handleBookmark} title="Toggle bookmark" ref={div}>
                <BookmarkSvg />
            </div>
            <div className="exhibitor-row__booth">
                {exhibitor.booths.map((booth: RegularBooth) => (
                    <div key={booth.name}>{booth.name}</div>
                ))}
            </div>
        </a>
    ));
};

export default ExhibitorRow;
