// src/components/List.tsx
import { useLocalStore, useObserver } from "mobx-react-lite";
import React, { useEffect } from "react";
import { uiState } from "../store";
import { Booth, BoothBase } from "../store/BoothStore";
import { Category } from "../store/CategoryStore";
import { Exhibitor } from "../store/ExhibitorStore";
import logger from "../tools/logger";
import { remsToPixels } from "../utils";
import BoothRow from "./BoothRow";
import CategoryRow from "./CategoryRow";
import ExhibitorRow from "./ExhibitorRow";
import "./List.scss";

const n = Math.ceil((Math.max(window.innerHeight, window.innerWidth) - remsToPixels(3.5 + 2)) / remsToPixels(3.5));
logger.log("List n:", n);

export default function List() {
    const s = useLocalStore(() => ({
        get items() {
            if (uiState.overlayShowsAll || uiState.listItems.length <= n) return uiState.listItems;
            return uiState.listItems.slice(0, n);
        }
    }));

    useEffect(() => {
        const el = document.querySelector(".list-row.active");
        if (el) el.scrollIntoView({ block: "nearest", inline: "nearest" });
    }, []);

    function mapItem(item: Booth | Category | Exhibitor, index: number) {
        const cls = `list-row ${index === uiState.activeListIndex ? "active" : ""}`;
        if (item instanceof Exhibitor) {
            return <ExhibitorRow exhibitor={item} key={`e${item.id}`} className={cls} />;
        } else if (item instanceof BoothBase) {
            return <BoothRow booth={item} key={`b${item.id}`} className={cls} />;
        } else if (item instanceof Category) {
            return <CategoryRow category={item} key={`c${item.id}`} className={cls} />;
        }
    }

    return useObserver(() => <div>{s.items.map(mapItem)}</div>);
}

// src/components/List.vue
<template>
    <div>
        <template v-for="(item, index) in items">
            <ExhibitorRow :exhibitor='item.obj' :key="`e${item.obj.id}`" v-if='item.type === "exhibitor"' class='list-row'
                :class='{active: index === activeListIndex}' />
            <CategoryRow :category='item.obj' :key="`c${item.obj.id}`" v-else-if='item.type === "category"' class='list-row'
                :class='{active: index === activeListIndex}' />
            <BoothRow :booth='item.obj' :key="`c${item.obj.id}`" v-else-if='item.type === "booth"' class='list-row'
                :class='{active: index === activeListIndex}' />
        </template>
    </div>
</template>

<script lang="ts">
import { mapGetters, mapState } from "vuex";
import { rtp } from "@/utils";
import ExhibitorRow from "./ExhibitorRow.vue";
import CategoryRow from "./CategoryRow.vue";
import BoothRow from "./BoothRow.vue";

const n = Math.ceil((Math.max(window.innerHeight, window.innerWidth) - rtp(3.5 + 2)) / rtp(3.5));
__logger.log('List n:', n);

export default {
    components: { ExhibitorRow, CategoryRow, BoothRow },
    computed: {
        ...mapState(["overlayShowsAll", "activeListIndex"]),
        ...mapGetters(["listItems"]),
        items() {
            // __logger.log('', this.listItems)
            if (this.overlayShowsAll || this.listItems.length <= n) return this.listItems;
            return this.listItems.slice(0, n);
        },
    },
    updated: function () {
        const el = document.querySelector('.list-row.active');
        if (el) el.scrollIntoView({ block: "nearest", inline: "nearest" });
        // this.$nextTick(function () {
        //     __logger.log('activiting')

        // })
    },
    // watch: {
    //     activeListIndex(idx) {
    //         __logger.log('activeListIndex', idx);
    //         const el = document.querySelector('.list-row.active');
    //         if (el) el.scrollIntoView(false);
    //         window.setTimeout(() => {

    //         }, 1);
    //     }
    // }
};
</script>

<style lang="scss">
.list-row {
    border-top: solid 1px #ebebeb;
    min-height: 3.5rem;
    @media (hover: hover) {
        &.active {
            background: #eee;
        }
        &:hover,
        &.active:hover {
            background-color: #f1f1f1;
        }
    }
}
</style>
