// src/components/Menu.tsx
import copyToClipboard from "copy-to-clipboard";
import { VisibilityProperty } from "csstype";
import { useLocalStore, useObserver } from "mobx-react-lite";
import React, { MouseEvent } from "react";
import data from "../data";
import store, { categoryStore, exhibitorStore, uiState } from "../store";
import { Category } from "../store/CategoryStore";
import baseUrl from "../tools/base-data-url";
import logger from "../tools/logger";
import isIframe from "../utils/is-iframe";
import { useAutorun } from "../utils/mobx";
import "./Menu.scss";
import OverlayContent from "./OverlayContent";
import { t } from "../utils/i18n";

const logoUrl = baseUrl + data.logo;
logger.log("Logo url: ", logoUrl);

window.setTimeout(function () {
    const img = new Image();
    img.onload = () => {
        logger.log("Logo image loaded");
    };
    img.src = logoUrl;

    // const link = document.createElement("link");
    // link.href = logoUrl;
    // link.rel = "preload";
    // (link as any).as = "image";
    // document.head.appendChild(link);
}, 1500);

function Menu() {
    const s = useLocalStore(() => ({
        logoVisibility: "visible" as VisibilityProperty,
        shown: false,
        shownTimeout: undefined as number
    }));

    useAutorun(() => {
        if (!uiState.menu) {
            s.shown = false;
            if (s.shownTimeout) window.clearTimeout(s.shownTimeout);
        } else {
            s.shownTimeout = window.setTimeout(() => (s.shown = true), 1);
        }
    });

    function handleClick(e) {
        if (uiState.kiosk) return e.preventDefault();
    }

    const barContent = isIframe ? (
        <div className="menu__bar -empty"></div>
    ) : (
            <div className="menu__bar">
                <a className="menu__title" href={data.homeUrl} target="_blank" rel="noopener noreferrer" onClick={handleClick}>
                    <img
                        src={logoUrl}
                        onError={() => (s.logoVisibility = "hidden")}
                        style={{ visibility: s.logoVisibility }}
                        alt=""
                    />
                </a>
            </div>
        );

    const categories = categoryStore.categories.length ? (
        <>
            <div className="menu__item">{t("Categories")}</div>
            {categoryStore.categories.map(c => (
                <a
                    className="menu__cat"
                    href={`?${encodeURIComponent(c.slug)}`}
                    key={c.id}
                    onClick={handleCategoryClick.bind(window, c)}
                >
                    <div className="menu__cat-bullet">&bull;</div>
                    <div className="menu__cat-title">{c.name}</div>
                    <div className="menu__cat-count">{numOfExhibitors(c.id)}</div>
                </a>
            ))}
        </>
    ) : null;

    // TODO: replace a href="/#" with buttons everywhere
    return useObserver(() => {
        if (!uiState.menu) return null;

        return (
            <OverlayContent
                className={`menu ${s.shown ? "shown" : ""}`}
                bar={barContent}
                onClose={close}
                onBack={close}
                backMode="none"
            >
                <div className="menu__content">
                    <a href="/#" onClick={handleSearch} className="menu__item">
                        {t("Search")}<sup>3</sup>
                    </a>
                    {!uiState.kiosk && !isIframe && (
                        <a href={data.homeUrl} target="_blank" className="menu__item" rel="noopener noreferrer">
                            Event&nbsp;Home&nbsp;
                            <i className="fas fa-external-link" />
                        </a>
                    )}
                    {!uiState.kiosk && !isIframe && !!data.registerUrl && (
                        <a href={data.registerUrl} target="_blank" className="menu__item" rel="noopener noreferrer">
                            {t("Register to Attend")}
                            <i className="fas fa-external-link" />
                        </a>
                    )}
                    {!uiState.kiosk && exhibitorStore.exhibitors.length > 0 && (
                        <a href="?bookmarks" onClick={handleBookmarks} className="menu__item -bookmarks">
                            <span>
                                {t("Bookmarks")} <span>({exhibitorStore.bookmarked.length})</span>
                            </span>
                            {exhibitorStore.bookmarked.length ? (
                                <button onClick={shareBookmarks} className="fas fa-share-square" title={t("Share bookmarks")} />
                            ) : null}
                        </a>
                    )}
                    {!uiState.kiosk && (
                        <a href="/?-pdf" className="menu__item -pdf" onClick={handlePdf}>
                            {t("Download PDF")}
                        </a>
                    )}
                    {categories}
                </div>
            </OverlayContent>
        );
    });

    function shareBookmarks(e: MouseEvent) {
        e.stopPropagation();
        e.preventDefault();
        (e.target as HTMLButtonElement).blur();
        const loc = window.location;
        const url = `${loc.protocol}//${loc.host}/?b=` + exhibitorStore.bookmarked.map(x => x.id).join("|");
        copyToClipboard(url);
        alert(t("Link copied to clipboard"));
    }

    function close() {
        uiState.menu = false;
    }

    function numOfExhibitors(id: number) {
        return exhibitorStore.exhibitors.filter(e => e.categories.find(c => c.id === id)).length;
    }

    function handleSearch(e: MouseEvent) {
        e.preventDefault();
        close();
        store.selectSearch();
        window.setTimeout(() => {
            uiState.searchFocused = true;
        }, 1);
    }

    function handleBookmarks(e: MouseEvent) {
        e.preventDefault();
        store.clickBookmarks();
        store.moveToList();
    }

    function handlePdf(e: MouseEvent) {
        e.preventDefault();
        uiState.printingPdf = true;
    }

    function handleCategoryClick(c: Category, e: MouseEvent) {
        e.preventDefault();
        store.clickCategory(c);
    }
}

export default () => useObserver(() => <>{uiState.menu ? <Menu /> : null}</>);

// src/components/Menu.vue
<template>
    <OverlayContent v-if="show" @close='close' @back='close' back-mode='none' class="menu" :class='{shown}'>
        <template slot="bar">
            <div class="menu__bar">
                <a class="menu__title" :href="homeUrl" target="_blank">
                    <img :src="logoUrl" onerror="this.style.visibility='hidden'" />
                </a>
            </div>
        </template>
        <div class="menu__content">
            <a :href='homeUrl' target="_blank" class="menu__item"><i class="fas fa-home"></i> Event&nbsp;Home&nbsp;<i
                    class="fas fa-external-link"></i></a>
            <a href='' @click.prevent='handleSearch' class="menu__item"><i class="fas fa-search"></i> Search</a>
            <a href='?bookmarks' @click.prevent='$store.dispatch("clickBookmarks"); $store.dispatch("moveToList");'
                class="menu__item -bookmarks"><i class="fas fa-bookmark"></i>
                <span>Bookmarks ({{bookmarkedArray.length}})</span>
                <button @click.stop.prevent=' shareBookmarks' v-if='bookmarkedArray.length' class="fas fa-share-square"
                    title="Share bookmarks"></button>
            </a>
            <!-- <a href='?seminars' @click.prevent='$store.dispatch("clickSeminars");' class="menu__item"><i class="fas fa-graduation-cap"></i> Seminars</a> -->

            <div class="menu__item" v-if="categoriesArray.length">Categories</div>
            <a class="menu__cat" :href='"?" + encodeURIComponent(c.slug)' v-for="c in categoriesArray" :key="c.id"
                @click.prevent='$store.dispatch("clickCategory", c.id);'>
                <div class="menu__cat-bullet">&bullet;</div>
                <div class="menu__cat-title">{{c.name}}</div>
                <div class="menu__cat-count">{{numOfExhibitors(c.id)}}</div>
            </a>
        </div>
    </OverlayContent>
</template>

<script lang="ts">
import Vue from 'vue';
import { mapGetters, mapState } from "vuex";
import OverlayContent from "./OverlayContent.vue";
import copyToClipboard from 'copy-to-clipboard';
import baseUrl from '@/tools/base-data-url';

const logoUrl = baseUrl + __data.logo;

window.setTimeout(function () {
    const link = document.createElement("link");
    link.href = logoUrl;
    link.rel = "preload";
    (link as any).as = "image";
    document.head.appendChild(link);
}, 4000);

export default {
    components: { OverlayContent },
    data: () => ({
        homeUrl: __data.homeUrl,
        logoUrl,
        shown: false
    }),
    computed: {
        ...mapState(["menu"]),
        ...mapGetters(["categoriesArray", "bookmarkedArray"]),
        show() {
            return this.menu;
        }
    },
    watch: {
        show(s) {
            if (s) {
                Vue.nextTick(() => {
                    this.shown = true;
                });
            } else this.shown = false;
        }
    },

    methods: {
        shareBookmarks(e) {
            e.target.blur();
            const url = `${location.protocol}//${location.host}/?b=` + this.$store.getters.bookmarkedArray.join('|');
            copyToClipboard(url);
            alert("Link copied to clipboard.\nOpen it on another device to import bookmarks.");
        },
        close() {
            this.$store.commit("setMenu", false);
        },
        // selectText(name) {
        //     this.$store.dispatch("selectText", name);
        //     this.close();
        // },
        numOfExhibitors(id) {
            return this.$store.getters.exhibitorsArray.filter(e => e.categories.indexOf(id) !== -1).length;
        },
        handleSearch() {
            this.close();
            this.$store.dispatch("selectSearch");
            this.$nextTick(() => this.$store.commit("setSearchFocused", true));
        }
    }
};
</script>

<style lang="scss">
.menu.shown .menu__title > img {
    opacity: 1;
}
.expo-jtrade19 .menu__title {
    background: #2b2a29;
}
.expo-awslondon19 .menu__title,
.expo-awsamsterdam19 .menu__title,
.expo-awsstockholm19 .menu__title {
    background: rgb(47, 7, 122);
    background: linear-gradient(207deg, rgba(47, 7, 122, 1) 0%, rgba(175, 60, 119, 1) 47%, rgba(235, 97, 60, 1) 100%);
    padding-top: 1.5rem;
    padding-bottom: 1.5rem;
}
.expo-atxcws20 .menu__title {
    padding-top: 1rem;
    padding-bottom: 1rem;
    > img {
        max-height: 150px;
    }
}
.expo-expo .menu__title > img {
    padding-right: 2rem;
}
.expo-vaughanribfest19 .menu__title > img {
    width: auto;
}

.expo-sydneybuildexpo {
    .menu.shown .overlay-bar__close {
        color: #555 !important;
    }
    .menu__title {
        padding-top: 0;
        padding-bottom: 0.5rem;
        background: #bbbdc7;

        > img {
            max-height: 150px;
            width: auto;
        }
    }
}

.menu {
    background: #f1f1f1;
    &__title {
        display: block;
        padding: 2.5rem 1rem;
        font-size: 2rem;
        font-weight: 100;
        text-align: center;
        margin-right: -3rem;
        img {
            width: 220px;
            max-height: 100px;
            opacity: 0;
            transition: opacity 500ms;
        }
    }
    &__item {
        padding: 0.5rem 1rem;
        min-height: 3rem;
        display: block;
        font-weight: 700;
        display: flex;
        align-items: center;
        color: #555 !important;
        text-decoration: none !important;

        > i:nth-child(2) {
            font-size: 0.7em;
            color: #aaa;
        }

        > i:first-child {
            color: #999;
            min-width: 1.7rem;
            text-align: center;
            padding-right: 0.5rem;
        }
        &.-bookmarks {
            > span {
                flex-grow: 1;
            }
            > button {
                padding: 0 0.4rem 0 0.4rem;
                margin-right: -0.4rem;
                border: none;
                cursor: pointer;
                align-self: stretch;
                &:hover {
                    color: #000;
                }
            }
        }
    }

    &__content {
        a:hover {
            background: rgba(0, 0, 0, 0.05);
        }
    }

    &__cat {
        padding: 0.5rem 1rem;
        min-height: 2.5rem;
        display: flex;
        justify-content: space-between;
        /* align-items: center; */
        color: #444 !important;
        text-decoration: none !important;
        /* border-bottom: solid 1px #ddd; */
    }

    &__cat-bullet {
        width: 0.7rem;
        color: #aaa;
    }
    &__cat-title {
        /* border-bottom: dotted 1px #ccc; */
        flex-grow: 1;
        /* padding-left: 0.5rem; */
    }
    &__cat-count {
        color: #888;
        font-size: 0.9em;
        /* border-bottom: dotted 1px #ccc */
        /* font-weight: 500; */
    }
}
div.menu__item {
    border-top: solid 1px #ddd;
    padding-bottom: 0;
}
</style>
