// src/components/OverlayContent.vue
<template>
    <div class="overlay-content">
        <OverlayGrip v-if="overlayPosition === 'bottom'"/>
        <OverlayBar :scrolled='scrolled' @close='handleClose' :hide-close='hideClose' :back-mode='backMode' @back="$emit('back')">
            <slot name="bar" />
        </OverlayBar>
        <div class='overlay-content__scrollable' ref='scrollable'>
            <slot />
        </div>
    </div>
</template>

<script lang="ts">
import { mapGetters, mapState } from "vuex";
import OverlayBar from "./OverlayBar.vue";
import OverlayGrip from "./OverlayGrip.vue";
import PerfectScrollbar from "perfect-scrollbar";
import isScrollUgly from "@/utils/is-scroll-ugly";

export default {
    props: ["backMode", "hideClose"],
    data: () => ({
        scrolled: false
    }),
    components: {
        OverlayBar, OverlayGrip
    },
    computed: {
        ...mapState(["overlaySize"]),
        ...mapGetters(["overlayPosition"])
    },
    mounted() {
        const sel = this.$refs.scrollable;

        const setScrolled = () => {
            this.scrolled = sel.scrollTop > 0;
            console.log("scrolled", sel.scrollTop, this.scrolled);
        };

        let update: () => void;
        if (isScrollUgly) {
            const ps = new PerfectScrollbar(sel);
            update = () => ps.update;
            sel.addEventListener("ps-scroll-y", setScrolled);
        } else {
            update = setScrolled;
            sel.addEventListener("scroll", setScrolled);
        }

        window.addEventListener("resize", update);
        const observer = new MutationObserver(update);
        observer.observe(sel, { childList: true, subtree: true });
    },
    watch: {
        overlaySize: function(s) {
            if (s !== "full" && this.$refs.scrollable.scrollTop !== 0){
                this.$refs.scrollable.scrollTop = 0;
            }
        }
    },
    methods: {
        handleClose() {
            this.$emit("close");
        }
    }
};
</script>

<style lang="scss">
.overlay-content {
    height: 100%;
    display: flex;
    flex-direction: column;
    &__scrollable {
        flex-grow: 1;
        height: 1px;
        overflow-y: hidden;
        position: relative;

        .overlay.full & {
            overflow-y: scroll;
            -webkit-overflow-scrolling: touch;
        }
    }
}
</style>

// src/components/OverlayContent.tsx
import { observer } from "mobx-react-lite";
import PerfectScrollbar from "perfect-scrollbar";
import React, { ReactNode, useEffect, useRef, useState } from "react";
import { uiState } from "../store";
import isScrollUgly from "../utils/is-scroll-ugly";
import OverlayBar from "./OverlayBar";
import "./OverlayContent.scss";
import OverlayGrip from "./OverlayGrip";
import OverlayParticles from "./OverlayParticles";

const OverlayContent: React.FC<{
    bar: ReactNode;
    className: string;
    particles?: boolean;
    backMode: "back" | "menu" | "none";
    hideClose?: boolean;
    onBack: () => void;
    onClose: () => void;
}> = ({ bar, className, particles, backMode, hideClose, onBack, onClose, children }) => {
    const [scrolled, setScrolled1] = useState(false);
    const scrollable = useRef<HTMLDivElement>();

    useEffect(() => {
        const sel = scrollable.current;
        const setScrolled = () => {
            setScrolled1(sel.scrollTop > 0);
            // logger.log("scrolled", sel.scrollTop, scrolled);
        };

        let update: () => void;
        if (isScrollUgly) {
            const ps = new PerfectScrollbar(sel);
            update = () => ps.update();
            sel.addEventListener("ps-scroll-y", setScrolled);
        } else {
            update = setScrolled;
            sel.addEventListener("scroll", setScrolled);
        }

        window.addEventListener("resize", update);
        const observer = new MutationObserver(update);
        observer.observe(sel, { childList: true, subtree: true });

        return () => {
            window.removeEventListener("resize", update);
            observer.disconnect();
        };
    }, [scrollable]);

    useEffect(() => {
        if (uiState.overlaySize !== "full" && scrollable.current.scrollTop !== 0) {
            scrollable.current.scrollTop = 0;
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [uiState.overlaySize]);

    return (
        <div className={`overlay-content ${className}`} id="overlay-content">
            {particles ? <OverlayParticles /> : null}
            {uiState.overlayPosition === "bottom" ? <OverlayGrip /> : null}
            <OverlayBar scrolled={scrolled} onClose={onClose} hideClose={hideClose} backMode={backMode} onBack={onBack}>
                {bar}
            </OverlayBar>

            <div className="overlay-content__scrollable" ref={scrollable}>
                {children}
            </div>
        </div>
    );
};

export default observer(OverlayContent);
