// src/components/Search.tsx
import classNames from "classnames";
import { useLocalStore, useObserver } from "mobx-react-lite";
import React, { FocusEvent, KeyboardEvent, useEffect, useRef } from "react";
import data from "../data";
import store, { uiState, exhibitorStore } from "../store";
import { useAutorun } from "../utils/mobx";
import OverlayContent from "./OverlayContent";
import List from "./List";
import "./Search.scss";
// import logger from "../tools/logger";

function Search() {
    const el = useRef<HTMLDivElement>();

    const s = useLocalStore(() => ({
        elementTop: 0,
        get hideRealInput() {
            return uiState.overlayBottom ? this.elementTop > 50 || uiState.overlaySize !== "full" : false;
        },
        get text() {
            return uiState.list.type === "search" ? uiState.list.text : "";
        },
        get bottomFull() {
            return uiState.overlaySize === "full" && uiState.overlayPosition === "bottom";
        },
        get showClose() {
            return !!this.text;
        },
        get backMode() {
            return this.text ? "back" : "menu";
        },
        get placeHolder() {
            return exhibitorStore.exhibitors.length === 0
                ? `Search ${data.boothTerm.toLowerCase()}`
                : `Search company, ${data.boothTerm.toLowerCase()} or category`;
        }
    }));

    function getInput(): HTMLInputElement {
        return el.current.querySelector ? el.current.querySelector("input[type=search]") : null;
    }

    useAutorun(() => {
        if (uiState.overlaySize !== "full" && document.activeElement === getInput()) {
            getInput().blur();
        }
    });

    useAutorun(() => {
        const i = getInput();
        if (i && uiState.searchFocused && document.activeElement !== i) {
            i.focus();
        }
    });

    useEffect(() => {
        const setTop = () => {
            s.elementTop = el.current.getBoundingClientRect().top;
        };
        setTop();
        const intervalId = window.setInterval(setTop, 50);
        return () => window.clearInterval(intervalId);
    }, [s]);

    // useEffect(() => {
    //     const setPosition = () => {
    //         // if (!el.current.tagName) return;
    //         const newVal = el.current.getBoundingClientRect().top > 50;
    //         s.hideRealInput = newVal || uiState.overlaySize !== "full";
    //         // logger.log("s.hideRealInput", s.hideRealInput, uiState.overlaySize, el.current.getBoundingClientRect().top > 50)
    //     };
    //     setPosition();
    //     const intervalId = window.setInterval(setPosition, 50);
    //     return () => window.clearInterval(intervalId);
    // }, [s]);

    return useObserver(() => {
        const fakeInput = s.hideRealInput ? (
            <input type="search" placeholder={s.placeHolder} value={s.text} onFocus={handleReplicaFocus} readOnly />
        ) : null;
        const bar = (
            <div className="search__bar" ref={el}>
                <input
                    type="search"
                    className={classNames({ fixed: s.hideRealInput })}
                    placeholder={s.placeHolder}
                    value={s.text}
                    onChange={setText}
                    onKeyDown={handleKeydown}
                    onFocus={handleFocus}
                    onBlur={handleBlur}
                />
                {fakeInput}
            </div>
        );
        // console.log("Search", s.hideRealInput, s.text);
        return (
            <OverlayContent onClose={handleClose} onBack={handleBack} backMode={s.backMode} hideClose={!s.showClose} bar={bar}>
                <List />
            </OverlayContent>
        );
    });

    function setText() {
        const text = getInput().value;
        uiState.centerMap = true;
        uiState.activeListIndex = text ? 0 : -1;
        uiState.list = {
            type: "search",
            text,
            focused: document.activeElement === getInput()
        };
    }

    function handleFocus() {
        uiState.searchFocused = true;
    }

    function handleBlur() {
        uiState.searchFocused = false;
    }

    function handleKeydown(e: KeyboardEvent) {
        let delta = 0 as 0 | 1 | -1;
        switch (e.key) {
            case "Down":
            case "ArrowDown":
                delta = 1;
                break;
            case "Up":
            case "ArrowUp":
                delta = -1;
                break;
            case "Enter":
                e.preventDefault();
                store.openActiveListItem();
                return;
        }
        if (delta) {
            e.preventDefault();
            store.changeActiveListIndex(delta);
        }
    }

    function handleClose() {
        getInput().value = "";
        getInput().focus();
        setText();
    }

    function handleReplicaFocus(e: FocusEvent) {
        e.preventDefault();
        getInput().focus();
    }

    function handleBack() {
        getInput().value = "";
        setText();
        uiState.desiredOverlaySize = "medium";
    }
}

export default () =>
    useObserver(() => <>{!uiState.details && !uiState.menu && uiState.list.type === "search" ? <Search /> : null}</>);

// src/components/Search.vue
<template>
    <OverlayContent v-if="show" @close='handleClose' @back='handleBack' :back-mode='backMode' :hide-close='!showClose'>
        <template slot="bar">
            <div class="search__bar">
                <input type="search" :class={fixed:hideRealInput} :placeholder="placeHolder" :value="text" @input="setText"
                    @keydown="handleKeydown" @focus="handleFocus" @blur="handleBlur" />
                <input type="search" v-if="hideRealInput" :placeholder="placeHolder" :value="text" @focus.prevent="handleReplicaFocus" />
            </div>
        </template>
        <List />
    </OverlayContent>
</template>

<script lang="ts">
import { mapGetters, mapState } from "vuex";
import List from "./List.vue";
import OverlayContent from "./OverlayContent.vue";

export default {
    components: { OverlayContent, List },
    data: () => ({
        hideRealInput: true,
        placeHolder: `Search company, ${__data.boothTerm} or category`
    }),
    computed: {
        ...mapState(["list", "details", "menu", "overlaySize", "searchFocused"]),
        ...mapGetters(["overlayPosition"]),
        text() {
            return this.list.text;
        },
        show() {
            return !this.details && !this.menu && this.list.type === "search";
        },
        bottomFull() {
            return this.overlaySize === "full" && this.overlayPosition === "bottom";
        },
        showClose() {
            return !!this.text; // || this.bottomFull
        },
        backMode() {
            return this.text ? "back" : "menu";
        }
    },
    mounted() {
        const setPosition = () => {
            if (!this.$el.tagName) return;
            const newVal = this.$el.getBoundingClientRect().top > 50;
            this.hideRealInput = newVal || this.overlaySize !== "full";
        };
        setPosition();
        window.setInterval(setPosition, 50);
    },
    watch: {
        overlaySize: function (s) {
            if (s !== "full" && document.activeElement === this.getInput()) {
                this.getInput().blur();
            }
        },
        searchFocused: function (f) {
            const i = this.getInput();
            if (i && f && document.activeElement !== i) {
                i.focus();
            }
        }
    },
    methods: {
        setText() {
            const text = this.getInput().value;
            this.$store.commit('setCenterMap', true);
            this.$store.commit('setActiveListIndex', text ? 0 : -1);

            this.$store.commit("setList", {
                type: "search",
                text,
                focused: document.activeElement === this.getInput()
            });
        },
        handleKeydown(e) {
            // __logger.log('handleKeydown', e);
            let delta = 0;
            switch (e.key) {
                case "Down":
                case "ArrowDown":
                    delta = 1;
                    break;
                case "Up":
                case "ArrowUp":
                    delta = -1;
                    break;
                case "Enter":
                    e.preventDefault();
                    this.$store.dispatch("openActiveListItem");    
                    return;
            }
            if (delta) {
                e.preventDefault();
                this.$store.dispatch("changeActiveListIndex", delta);
            }
        },
        handleReplicaFocus() {
            this.getInput().focus();
        },
        handleClose() {
            // if (this.bottomFull) {
            //     this.handleBack();
            //     store.commit("setOverlaySize", "medium");
            // } else {
            //     this.getInput().value = "";
            //     this.getInput().focus();
            //     this.setText();
            // }
            this.getInput().value = "";
            this.getInput().focus();
            this.setText();
        },
        handleBack() {
            this.getInput().value = "";
            this.setText();
            store.commit("setOverlaySize", "medium");
        },
        handleBlur() {
            this.$store.commit("setSearchFocused", false);
        },
        handleFocus() {
            this.$store.commit("setSearchFocused", true);
        },
        getInput() {
            return this.$el.querySelector ? this.$el.querySelector("input[type=search]") : null;
        }
    }
};
</script>

<style lang="scss">
.search {
    &__bar {
        input {
            border: none;
            border-radius: 0.5rem;
            outline: none;
            height: $overlay-height;
            -webkit-appearance: none;
            -webkit-tap-highlight-color: transparent;
            width: 100%;
        }
        input::placeholder {
            color: #bbb;
        }

        input.fixed {
            opacity: 0;
            pointer-events: none;
            position: fixed;
            top: -100px;
        }
    }
}
</style>
