// src/components/Map/Map.tsx
import classNames from "classnames";
import { easeExpOut } from "d3-ease";
import { interpolate } from "d3-interpolate";
import { event as currentEvent, select } from "d3-selection";
import { zoom, zoomIdentity, zoomTransform, ZoomTransform } from "d3-zoom";
import { useLocalStore, useObserver } from "mobx-react-lite";
import React, { useEffect, useRef } from "react";
import { m4 } from "twgl.js";
import Rect from "../../core/Rect";
import store, { uiState } from "../../store";
import { Booth } from "../../store/BoothStore";
import logger from "../../tools/logger";
import { useReaction } from "../../utils/mobx";
import getBoothIdFromClientXy from "./booth-by-xy";
import createDrawer, { Drawer } from "./drawing/Drawer1";
import "./Map.scss";
import { sizeCanvasToParentElement } from "./utils";
import zoomBound from "./zoom-bound";
import configInertia from "./zoom-inertia";
import isIframe from "../../utils/is-iframe";
import isMac from "../../utils/is-mac";

//console.log('isIframe', isIframe)

export default function Map() {
    let zoomAf: number;
    let zoomAfTransform: ZoomTransform;
    // do not use useState unless really needed
    const el = useRef<HTMLCanvasElement>();
    // use mobx for everything
    const s = useLocalStore(() => ({
        animatePlease: false,
        moving: false,
        $canvas: null as d3.Selection<HTMLCanvasElement, unknown, null, undefined>,
        zoom: null as d3.ZoomBehavior<Element, unknown>,
        drawer: null as Drawer,
        prevBoothOver: null as Booth
        // get visibleRect() {
        //     const rect = uiState.canvasVisibleRectPx
        //     return  rect;//rect.withPadding(rect.w * 0.05, rect.h * 0.05);
        // }
    }));

    // init
    useEffect(init, []);
    useReaction(
        () => uiState.devicePixelRatio,
        () => {
            s.drawer.setPixelRatio(uiState.devicePixelRatio);
        }
    );

    // useReaction(
    //     () => uiState.canvasVisibleRectPx,
    //     ()=>{
    //         if (!s.drawer) return;
    //         const v = uiState.canvasVisibleRectPx;
    //         s.drawer.setVisibleRect(v.scale(uiState.devicePixelRatio));
    //         zoomBoundCurrent();
    //     }
    // );

    useReaction(
        () => [uiState.canvasVisibleRectPx, s.drawer],
        () => {
            if (!s.drawer) return;
            const v = uiState.canvasVisibleRectPx;
            logger.log("visibleRect change", v);
            s.drawer.setVisibleRect(v.scale(uiState.devicePixelRatio));
            // rezoom to make it fit bounds
            // this.$canvas.call(this.zoom.transform, zoomTransform(this.$canvas.node()));
            zoomBoundCurrent();
        },
        { fireImmediately: true }
    );

    useReaction(
        () => uiState.centerMap,
        () => {
            if (!uiState.centerMap) return;
            uiState.centerMap = false;
            zoomTo(zoomIdentity);
        }
    );

    useReaction(
        () => uiState.zoomBy,
        () => {
            if (!uiState.zoomBy) return;
            const z = uiState.zoomBy;
            uiState.zoomBy = null;
            s.animatePlease = true;
            s.$canvas.call(s.zoom.scaleBy as any, z === -1 ? 0.66 : 1.5);
        }
    );

    useReaction(
        () => uiState.moveToBooths,
        () => {
            logger.log("this.moveToBooths", uiState.moveToBooths);
            if (!uiState.moveToBooths) return;
            //this.handledMoveToExhibitor = uiState.moveToBooths;
            logger.log("watched moveToBooths", uiState.moveToBooths);
            // // ask map to move to this exhibitor
            const rects = uiState.moveToBooths.map(b => b.rect) as Rect[];
            if (rects.length === 0) return;
            const r = Rect.fromMultiple(rects);
            const zoomScale = zoomTransform(s.$canvas.node()).k; //m.getZoomTransform().k;
            const z = getTramsformToCenterSvgRect(r, uiState.canvasVisibleRectPx, Math.max(zoomScale, 3));
            zoomTo(z);

            uiState.moveToBooths = null;
            // store.commit("setMoveToBooths", null);
            // this.handledMoveToExhibitor = null;
        }
    );

    return useObserver(() => (
        <canvas
            ref={el}
            className={classNames({ map: true, moving: s.moving })}
            onMouseMove={handleMouseMoveAndOver}
            onClick={handleClick}
            onMouseOver={handleMouseMoveAndOver}
            onMouseOut={handleMouseOut}
        >
            ExpoFP.com
        </canvas>
    ));

    function init() {
        s.$canvas = select(el.current);

        s.zoom = zoom()
            .clickDistance(15)
            .interpolate(interpolate)
            .scaleExtent([0.1, 12])
            .constrain((transform, extent, translateExtent) => zoomBound(s.drawer, transform, false))
            .filter(function() {
                if (!isIframe || !currentEvent || currentEvent.type !== "wheel")
                    // && currentEvent.type !== "touchstart"
                    return true;

                const preventWheel = currentEvent.type === "wheel" && !currentEvent.ctrlKey && !currentEvent.metaKey;
                //||(currentEvent.type === "touchstart" && currentEvent.touches.length < 2);

                if (preventWheel) {
                    // if (currentEvent.type === "touchstart") {
                    //     scheduleMessage("Use two fingers to move", 500);
                    // } else

                    if (isMac) {
                        uiState.largeMessage = "Use ⌘ + scroll to zoom";
                    } else {
                        uiState.largeMessage = "Use Ctrl + scroll to zoom";
                    }
                    uiState.largeMessageLastSet = performance.now();
                }

                return !preventWheel;
            })
            .on("zoom", () => {
                const t = currentEvent.transform;
                const isWheel = currentEvent.sourceEvent && currentEvent.sourceEvent.type === "wheel";
                if (isWheel || s.animatePlease) setZoomTransformAnimated(t, 300, easeExpOut);
                //s.drawer.setZoomTransform(t);
                else if (t.animate) setZoomTransformAnimated(t, 500, easeExpOut);
                else setZoomTransformAnimated(t, 0, null);
                s.animatePlease = false;
                s.moving = true;
            })
            .on("end", () => {
                s.moving = false;
            });

        configInertia(s.zoom);
        //m.setVisibleRect(thiuiState.canvasVisibleRectPx);
        sizeCanvasToParentElement(el.current);
        s.drawer = createDrawer(el.current, true);

        // s.drawer.setVisibleRect((uiState.canvasVisibleRectPx as Rect).scale(uiState.devicePixelRatio));
        s.drawer.setPixelRatio(uiState.devicePixelRatio);
        window.addEventListener("resize", () => {
            // __logger.log('canvas change', canvas);
            sizeCanvasToParentElement(el.current);
            s.drawer.resetCanvasSize();
        });
        setZoomTransformAnimated(zoomIdentity, 0, null);
        s.$canvas.call(s.zoom as any);
    }

    function raiseBoothOver(b: Booth) {
        if (s.prevBoothOver === b) return;
        s.prevBoothOver = b;
        uiState.hoveredBooth = b;
    }

    function handleMouseMoveAndOver(e) {
        const b = getBoothIdFromClientXy(e.clientX, e.clientY, s.drawer);
        // console.log("handleMouseMoveAndOver", b);
        raiseBoothOver(b);
    }

    function handleMouseOut(e) {
        raiseBoothOver(undefined);
    }

    function handleClick(e: React.MouseEvent) {
        if (uiState.overlayPosition === "bottom" && uiState.overlaySize === "full") {
            store.showMap();
        }
        // if (!this.props.onBoothClick) return;
        const b = getBoothIdFromClientXy(e.clientX, e.clientY, s.drawer);
        logger.log("click", b);
        store.clickBooth(b);
    }

    function zoomTo(transform: ZoomTransform) {
        const t = zoomTransform(s.$canvas.node());
        if (t.x === transform.x && t.y === transform.y && t.k === transform.k) return;
        (transform as any).animate = true;
        s.$canvas.call(s.zoom.transform as any, transform);
    }

    function zoomBoundCurrent() {
        const ct = zoomTransform(s.$canvas.node());
        const nt = zoomBound(s.drawer, ct, false);
        if (nt !== ct) {
            // __logger.log('fixed bounds', ct, nt)
            zoomTo(nt);
        }
    }

    function setZoomTransformAnimated(t: ZoomTransform, duration: number, easingFunc: (k: number) => number) {
        // animate from existing position to dest
        if (zoomAf) {
            // move to the last frame zoom transform
            cancelAnimationFrame(zoomAf);
            // s.drawer.setZoomTransform(zoomAfTransform);
        }
        if (!duration) {
            zoomAfTransform = undefined;
            s.drawer.setZoomTransform(t);
            return;
        }
        const ct = zoomAfTransform || s.drawer.getZoomTransform();
        const i = interpolate(ct, t);
        const start = performance.now();

        function animationStep() {
            const part = Math.min(1, (performance.now() - start) / duration);
            const easedPart = easingFunc ? easingFunc(part) : part;
            const val = i(easedPart);
            s.drawer.setZoomTransform(val);
            if (part !== 1) {
                zoomAf = requestAnimationFrame(animationStep);
            } else {
                zoomAf = undefined;
                zoomAfTransform = undefined;
                logger.log("setZoomTransformAnimated ended", part);
            }
        }
        zoomAfTransform = t;
        animationStep();
    }

    function getTramsformToCenterSvgRect(svgRect: Rect, vRect: Rect, maxZoom: number) {
        const minPaddingPercent = 5;

        const targetRect = vRect.withPadding((vRect.w * minPaddingPercent) / 100, (vRect.h * minPaddingPercent) / 100);

        const svgPxMatrix = s.drawer.getSvgPxUnzoomedMatrix();

        const xy1 = m4.transformPoint(svgPxMatrix, [svgRect.x1, svgRect.y1, 1], null);
        const x1 = xy1[0],
            y1 = xy1[1];
        const xy2 = m4.transformPoint(svgPxMatrix, [svgRect.x2, svgRect.y2, 1], null);
        const x2 = xy2[0],
            y2 = xy2[1];
        const bSvgRect = Rect.fromX1y1x2y2(x1, y1, x2, y2);

        // __logger.log(bSvgRect.w, bSvgRect.h, bSvgRect);

        // get max zoom
        const zoom = Math.min(targetRect.w / bSvgRect.w, targetRect.h / bSvgRect.h, maxZoom);

        const diffX = targetRect.cx - bSvgRect.cx * zoom;
        const diffY = targetRect.cy - bSvgRect.cy * zoom;
        const t = zoomIdentity.translate(diffX, diffY).scale(zoom); // { x: diffX, y: diffY, k: zoom };
        return zoomBound(s.drawer, t, true);
    }
}

// src/components/Map_OLD/Map.vue
<template>
    <canvas class="map" @mousemove="handleMouseMove" @click="handleClick" @mouseover="handleMouseOver" @mouseout="handleMouseOut">
        I'm map
    </canvas>
</template>

<script lang="ts">
import { mapGetters, mapState } from "vuex";
import { initialize, requireRedraw, applyZoomTransform, getBoothIdFromClientXy, setVisibleRect } from "./draw";
//import { ZoomBehavior } from "d3";
import { remsToPixels } from "./utils";
import c from "./drawing-context";

export default {
    name: "Map",
    data: () => ({}),
    computed: {
        ...mapState(["overlaySize", "moveToBooths", "booths", "hoveredBooth", "screenSize", "bookmarked"]),
        ...mapGetters(["overlayPosition", "exhibitorsArray", "listBoothsIds", "selectedBoothIds", "hoveredBoothIds"]),
        visibleRect() {
            // console.log("get visibleRect", this.occupied);
            const w = this.screenSize.width;
            const h = this.screenSize.height;

            switch (this.overlayPosition) {
                case "left":
                    return Rect.fromX1y1x2y2(remsToPixels(21), 0, w, h);
                // case "bottomSmall":
                //     return Rect.fromX1y1x2y2(0, 0, w, h - remsToPixels(4));
                case "bottom":
                    return Rect.fromX1y1x2y2(0, 0, w, h - remsToPixels(12));
            }

            throw new Error("Not supported `overlayPosition`");
        }
    },
    mounted() {
        const canvas = this.$el;
        // const $parent = d3.select(canvas.parentElement);
        this.$canvas = d3.select(canvas);
        this.zoom = d3
            .zoom()
            .clickDistance(15)
            .scaleExtent([0.8, 8])
            .on("zoom", () => applyZoomTransform(d3.event.transform));
        this.$canvas.call(this.zoom);

        initialize(canvas, this.visibleRect);
    },
    watch: {
        moveToBooths: function() {
            if (!this.moveToBooths) return;
            // this.handledMoveToExhibitor = this.moveToBooths;
            console.log("watched moveToBooths", this.moveToBooths);
            // ask map to move to this exhibitor
            const rects = this.moveToBooths.map(id => this.booths[id].rect) as Rect[];
            if (rects.length === 0) return;
            var r = Rect.fromMultiple(rects);
            const z = getZoomToCenterSvgRect(r, Math.max(c.zoomScale, 1.2));
            const destZoom = d3.zoomIdentity.translate(z.x, z.y).scale(z.k);
            this.$canvas
                .transition()
                .duration(200)
                .call(this.zoom.transform, destZoom);

            store.commit("setMoveToBooths", null);
            // this.handledMoveToExhibitor = null;
        },
        hoveredBoothIds: () => requireRedraw(),
        selectedBoothIds: () => requireRedraw(),
        bookmarked: () => requireRedraw(),
        listBoothsIds: () => requireRedraw(),
        visibleRect: v => setVisibleRect(v)
    },
    methods: {
        raiseBoothOver(id) {
            id = id || null;
            if (this.prevBoothOver === id) return;
            this.prevBoothOver = id;
            this.$store.commit("setHoveredBooth", id);
        },
        handleMouseMove(e) {
            const id = getBoothIdFromClientXy(e.clientX, e.clientY);
            this.raiseBoothOver(id);
        },
        handleMouseOver(e) {
            const id = getBoothIdFromClientXy(e.clientX, e.clientY);
            this.raiseBoothOver(id);
        },
        handleMouseOut(e) {
            this.raiseBoothOver(undefined);
        },
        handleClick(e) {
            if (this.overlayPosition === "bottom" && this.overlaySize === "full") {
                this.$store.dispatch("showMap");
            }
            //if (!this.props.onBoothClick) return;
            const id = getBoothIdFromClientXy(e.clientX, e.clientY);
            console.info("click", id);
            this.$store.dispatch("clickBooth", id);
        }
    }
};

// function getZoomToCenterSvgRect(svgRect: Rect, zoom: number) {
//     const { cx, cy } = svgRect;

//     const browserCx = c.visibleBRect.cx;
//     const browserCy = c.visibleBRect.cy;

//     const svgBcx = svgRect.cx * c.fpScale + c.fpCxUnzoomed;
//     const svgBcy = svgRect.cy * c.fpScale + c.fpCyUnzoomed;

//     const diffX = browserCx - svgBcx * zoom;
//     const diffY = browserCy - svgBcy * zoom;

//     return { x: diffX, y: diffY, k: zoom };
// }

function getZoomToCenterSvgRect(svgRect: Rect, maxZoom: number) {
    const minPaddingPercent = 5;

    const targetRect = c.visibleBRect.withPadding(
        (c.visibleBRect.w * minPaddingPercent) / 100,
        (c.visibleBRect.h * minPaddingPercent) / 100
    );

    const bSvgRect = c.sRectToBrowserUnzoomed(svgRect);

    // get max zoom
    const zoom = Math.min(targetRect.w / bSvgRect.w, targetRect.h / bSvgRect.h, maxZoom);

    const diffX = targetRect.cx - bSvgRect.cx * zoom;
    const diffY = targetRect.cy - bSvgRect.cy * zoom;

    return { x: diffX, y: diffY, k: zoom };
}
</script>

<style scoped>
</style>
